<a href="https://colab.research.google.com/github/JulioFMDB/cursopython/blob/main/Aula%206%20e%207%20Curso%20Target.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

# **Curso de Lógica de Programação Python - Parte 3**

$B$ $\gt$ $\frac{1}{n}$$\sum\limits_{i=1}^{n}x_1$

![image.png]()
### $Instrutor:$ [**Diego Bilhalva**](https://www.diegobilhalva.com)

---



![image.png](https://targettrust.com.br/wp-content/themes/bones/library/images/logo-novo.png)

---
---

## **3 Estruturas de Dados e Sequências, Funções e Arquivos**

Discutiremos nesta seção os conceitos basilares para manipulação de dados e iterações em **Python**. Embora a linguagem conte com um razoável número de bibliotecas mais robustas e com funcionalidades bastante avançadas para este tipo de tarefa, tais ferramentas foram desenvolvidas e projetadas utilizando estes conceitos. 

As estruturas, vocês verão, são extremamente simples e dominá-las é algo imprescindível durante sua jornada como **Cientista de Dados**. Vejamos!

### **3.1 Tuplas**

Já vimos antes que **tuplas** são objetos imutáveis do Python, com tamanho fixo.
Para criar uma tupla, basta declarar uma variável e atribuir um série de valores separadas por vírgula. Veja:

In [ ]:
tupla = 1, 2, 3, 4
tupla

(1, 2, 3, 4)

In [ ]:
tupla = (1, 2, 3, 4)
tupla

(1, 2, 3, 4)

In [ ]:
tupla_aninhada = (1,2,3), ('a', 'b')
tupla_aninhada

((1, 2, 3), ('a', 'b'))

In [ ]:
tupla_aninhada = ((1,2,3), ('a', 'b'))
tupla_aninhada

((1, 2, 3), ('a', 'b'))

In [ ]:
tupla_listas = [1,2,3], ['a', 'b']
tupla_listas

([1, 2, 3], ['a', 'b'])

In [ ]:
tupla_complexa = [1,2,3], ['a', 'b'], True, 'chuva', 7, (1, 'a')
tupla_complexa

([1, 2, 3], ['a', 'b'], True, 'chuva', 7, (1, 'a'))

In [ ]:
tupla_complexa

([1, 2, 3], ['chuva', 43], True, 'chuva', 7, (1, 'a'))

Alem disso, podemos passar um iterador qualquer como argumento da função $tuple()$ e como resultado teremos uma **tupla**. Observe:

In [ ]:
tupla = tuple(range(10))
tupla

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [ ]:
lista = [1,2,3]
type(lista)

list

In [ ]:
tupla2 = tuple(lista)
type(tupla2)

tuple

In [ ]:
tupla2

(1, 2, 3)

In [ ]:
nome = 'Diego'
print(tuple(nome)) #NLP - inteligência artificial

('D', 'i', 'e', 'g', 'o')

Para acessar os elementos de uma **tupla**, assim como outras linguagens $C$, $C++$, $Java$ e outras linguagens, basta utilizar colchetes $[$ $]$ passando o índice do elemento como argumento. Veja:

In [ ]:
tupla[4]

4

Conforme vimos anteriormente, a **tupla** pode conter ela própria objetos mutáveis, tais como uma **lista**. Estes objetos podem ser alterados *in-place* conforme abaixo:

In [ ]:
tupla_complexa

([1, 2, 3], ['chuva', 43], True, 'chuva', 7, (1, 'a'))

In [ ]:
tupla_complexa[0] #acessando o elemento de posição 0

[1, 2, 3]

In [ ]:
tupla_complexa[0][2] #acessando o elemento de posição 2

3

In [ ]:
tupla_complexa[0][2] = 'sol'
tupla_complexa

([1, 2, 'sol'], ['chuva', 43], True, 'chuva', 7, (1, 'a'))

In [ ]:
tupla_complexa[2]

True

In [ ]:
tupla_complexa[2] = False

TypeError: ignored

**Desempacotando Tuplas**

In [ ]:
len(tupla_complexa)

6

In [ ]:
a, b, c, d, e, f = tupla_complexa

In [ ]:
b

['chuva', 43]

In [ ]:
b[0]

'chuva'

In [ ]:
tupla2 = 1, 2, ('a', 4, '3')
tupla2

(1, 2, ('a', 4, '3'))

In [ ]:
x, y, z = tupla2
print(x)
print(y)
print(z)

1
2
('a', 4, '3')

In [ ]:
x, y, (a, b, c) = tupla2
print(x)
print(y)
print(a)
print(b)
print(c)

1
2
a
4
3

**Método $count()$**

Este método conta quantas vezes o argumento passado está presente na tupla.

In [ ]:
tupla = 0, 'a', 1, 1, 2, 3, 5, 'a', 'a', 4, 'ab'

In [ ]:
tupla.count('a')

3

### **3.2 Listas**

Também já analisamos implicitamente as **Listas**, no entanto agora cabe ressaltar que diferentemente das **Tuplas**, que possuem tamanhos fixos e seu conteúdo não pode ser modificado _in-place_, as **Listas** são o completemente oposto, pois tem tamanho variável, além de permitir que seus valores seja alterados _in-place_.

Listas podem ser constituidas de modo homogêneo

In [ ]:
lista1 = [1,2,3]
lista1

[1, 2, 3]

ou heterogênea

In [ ]:
lista2 = ['a', 1, True, 1.453]
lista2

['a', 1, True, 1.453]

E assim como as *tuplas*, **podemos criar uma lista a partir de um iterador** com a função $list()$. Veja:

In [ ]:
lista = list(tupla)
print(lista)
print(type(lista))

[0, 'a', 1, 1, 2, 3, 5, 'a', 'a', 4, 'ab']
<class 'list'>

In [ ]:
print(tupla)
print(type(tupla))

(0, 'a', 1, 1, 2, 3, 5, 'a', 'a', 4, 'ab')
<class 'tuple'>

**Adicionando e removendo elementos**

Elementos podem ser adicionados ao final da lista. Observe:

In [ ]:
lista.append('elemento x')

In [ ]:
lista

[0, 'a', 1, 1, 2, 3, 5, 'a', 'a', 4, 'ab', 'elemento x']

In [ ]:
lista.append('elemento y')
lista

[0, 'a', 1, 1, 2, 3, 5, 'a', 'a', 4, 'ab', 'elemento x', 'elemento y']

[0, 'a', True, 1, 1, 2, 3, 5, 'a', 'a', 4, 'ab', 'elemento x', 'elemento y']

Podemos adicionar um elemento em qualquer posição da lista também. Veja:

In [ ]:
lista.insert(2, True)
lista

[0,
 'a',
 True,
 True,
 1,
 1,
 2,
 3,
 5,
 'a',
 'a',
 4,
 'ab',
 'elemento x',
 'elemento y']

In [ ]:
lista.insert(99, True)
lista

[0,
 'a',
 True,
 True,
 1,
 1,
 2,
 3,
 5,
 'a',
 'a',
 4,
 'ab',
 'elemento x',
 'elemento y',
 True]

In [ ]:
lista.insert(len(lista), 'teste')
lista

[0,
 'a',
 True,
 True,
 1,
 1,
 2,
 3,
 5,
 'a',
 'a',
 4,
 'ab',
 'elemento x',
 'elemento y',
 True,
 True,
 'teste']

In [ ]:
lista.append('elemento y')
lista

[0,
 'a',
 True,
 True,
 1,
 1,
 2,
 3,
 5,
 'a',
 'a',
 4,
 'ab',
 'elemento x',
 'elemento y',
 True,
 True,
 'teste',
 'elemento y']

O índice de inserção deve estar entre 0 e o tamanho da lista, inclusive.

O oposto do método $insert()$ é o método $pop()$. Para remover um elemento específico, basta passar por _argumento_ o índice deste elemento.

In [ ]:
lista.pop(len(lista)-1)

'elemento y'

In [ ]:
a = lista.pop(6)
a

2

In [ ]:
lista

[0,
 'a',
 True,
 True,
 1,
 1,
 3,
 5,
 'a',
 'a',
 4,
 'ab',
 'elemento x',
 'elemento y',
 True,
 True,
 'teste']

Agora imagine que você deseje remover um elemento sem se preocupar com a posição com que ele se encontre. Para isto, utilize o camando $remove()$ que localizará a primeira ocorrência deste elemento e o eliminará. Veja:

In [ ]:
lista.remove('teste')
lista

[0,
 'a',
 True,
 True,
 1,
 1,
 3,
 5,
 'a',
 'a',
 4,
 'ab',
 'elemento x',
 'elemento y',
 True,
 True]

In [ ]:
lista.remove('a')
lista

[0,
 True,
 True,
 1,
 1,
 3,
 5,
 'a',
 'a',
 4,
 'ab',
 'elemento x',
 'elemento y',
 True,
 True]

Podemos **combinar listas** também. Veja:

In [ ]:
lista1 = [1,2,3]
lista2 = ['a','b', 'c']

lista3 = lista1 + lista2
lista3

[1, 2, 3, 'a', 'b', 'c']

In [ ]:
lista4 = ["x", 'y', 3]

lista3.extend(lista4)

lista3

[1, 2, 3, 'a', 'b', 'c', 'x', 'y', 3]

In [ ]:
lista3.extend((1,2)) #desfaz a tupla e a insere com n elementos a + na lista

In [ ]:
lista3.extend('diego')
lista3

[1, 2, 3, 'a', 'b', 'c', 'x', 'y', 3, 1, 2, 'd', 'i', 'e', 'g', 'o']

**Ordenação**:

In [ ]:
lista3.sort()

TypeError: ignored

In [ ]:
lista = []

In [ ]:
lista.extend('meu nome é diego e eu sou um data scientist')

In [ ]:
lista

['d',
 'e',
 'g',
 'i',
 'o',
 'm',
 'e',
 'u',
 ' ',
 'n',
 'o',
 'm',
 'e',
 ' ',
 'é',
 ' ',
 'd',
 'i',
 'e',
 'g',
 'o',
 ' ',
 'e',
 ' ',
 'e',
 'u',
 ' ',
 's',
 'o',
 'u',
 ' ',
 'u',
 'm',
 ' ',
 'd',
 'a',
 't',
 'a',
 ' ',
 's',
 'c',
 'i',
 'e',
 'n',
 't',
 'i',
 's',
 't']

In [ ]:
lista.sort()
lista

[' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'a',
 'a',
 'c',
 'd',
 'd',
 'd',
 'e',
 'e',
 'e',
 'e',
 'e',
 'e',
 'e',
 'g',
 'g',
 'i',
 'i',
 'i',
 'i',
 'm',
 'm',
 'm',
 'n',
 'n',
 'o',
 'o',
 'o',
 'o',
 's',
 's',
 's',
 't',
 't',
 't',
 'u',
 'u',
 'u',
 'u',
 'é']

**Fatiamento (slicing)**:

In [ ]:
lista[14:]

['d',
 'e',
 'e',
 'e',
 'e',
 'e',
 'e',
 'e',
 'g',
 'g',
 'i',
 'i',
 'i',
 'i',
 'm',
 'm',
 'm',
 'n',
 'n',
 'o',
 'o',
 'o',
 'o',
 's',
 's',
 's',
 't',
 't',
 't',
 'u',
 'u',
 'u',
 'u',
 'é']

In [ ]:
lista[:14]

[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'a', 'a', 'c', 'd', 'd']

In [ ]:
lista[14:20]

['d', 'e', 'e', 'e', 'e', 'e']

In [ ]:
lista = list(range(20))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
lista[::2]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

Agora veja bem os exemplos a seguir:

In [ ]:
lista[:len(lista)-5]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

**Step**:

In [ ]:
lista[::2] #imprimir os valores pares

In [ ]:
lista[::-1] #lista invertida

[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
lista[::-3]

[19, 16, 13, 10, 7, 4, 1]

In [ ]:
listab = [5,2, 6,2,1,7,9,5,2,5]
listab[::2]

[5, 6, 1, 9, 2]

**Método index()**

In [ ]:
listab.insert(4,'Diego')
listab

[5, 2, 6, 2, 'Diego', 1, 7, 9, 5, 2, 5]

In [ ]:
if 'Diego' in listab:
  indice = listab.index('Diego')
  valor = listab.pop(indice)


print(indice)
print(valor)

4
Diego

In [ ]:
listab.insert(indice,'Diego')
listab

[5, 2, 6, 2, 'Diego', 1, 7, 9, 5, 2, 5]

**#dicaTT / #dicadoBilly**: dá para pensar e realizar algumas operações com *strings* como se fossem *listas*. Veja:

In [ ]:
frase = 'o Diego é meu amigo'
nome = frase[2:7]

'Diego'

In [ ]:
nome[::-1]

'ogeiD'

In [ ]:
frase.find('meu')

-1

In [ ]:
frase.index('Augusto')

ValueError: ignored

No entanto, diferente da string não podemos atribuir valores às posições. Para alterar um valor numa string, usamos o método $replace()$:

In [ ]:
frase[2:7] = 'Augusto'

TypeError: ignored

In [ ]:
frase.replace('Diego', 'Augusto')

'o Augusto é meu amigo'

In [ ]:
frase = 'o {0} é meu amigo'.format('Diego')
frase

'o Diego é meu amigo'

**Enumerate**:

Imagina que você quer criar um dicionário (assunto que veremos em breve), para controlar os índices atuais dos elementos de uma _lista_ ou _tupla_. Uma maneira de se fazer é conforme abaixo:

In [ ]:
i = 0

mapping = {}

lista = ['fulano', 'sicrano', 'beltrano']

for elemento in lista:
  print(elemento)
  mapping[i] = elemento
  i += 1

mapping

fulano
sicrano
beltrano

{0: 'fulano', 1: 'sicrano', 2: 'beltrano'}

In [ ]:
mapping[1]

'sicrano'

In [ ]:
dicionario = {
    'nome': 'Diego'
    ,'endereco': 'Sapucaia do Sul'
    ,'telefone': '5122222222'
}

In [ ]:
dicionario['telefone']

'5122222222'

Como o uso deste tipo de recurso é bem comum, principalmente quando se trabalha com manipulação de dados, a comunidade de desenvolvedores do **Python** resolveram nos presentear com a *função embutida* $enumerate$. Veja:

In [ ]:
lista = ['fulano', 'sicrano', 'beltrano']

mapping = {}

for i, elemento in enumerate(lista):
  mapping[i] = elemento

mapping

{0: 'fulano', 1: 'sicrano', 2: 'beltrano'}

**Sorted**:

Devolve uma nova lista ordenada dos elementos de qualquer _lista_ ou _tupla_. Observe:

In [ ]:
lista = [234, 34, 54,67,854]
sorted(lista)

[34, 54, 67, 234, 854]

In [ ]:
lista

[234, 34, 54, 67, 854]

In [ ]:
lista.sort()
lista

[34, 54, 67, 234, 854]

In [ ]:
lista = [234, 34, 54,67,854]
print(sorted(lista, reverse=True))
print(lista)

[854, 234, 67, 54, 34]
[234, 34, 54, 67, 854]

Olha que interessante:

In [ ]:
frase2 = 'eu sou um futuro data scientist'
sorted(frase2) #NLP

[' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'a',
 'a',
 'c',
 'd',
 'e',
 'e',
 'f',
 'i',
 'i',
 'm',
 'n',
 'o',
 'o',
 'r',
 's',
 's',
 's',
 't',
 't',
 't',
 't',
 'u',
 'u',
 'u',
 'u',
 'u']

In [ ]:
frase2

'eu sou um futuro data scientist'

**Reversed**:

Ao contrário da função $sorted()$, a função $reversed()$ atua sobre a _lista_, _tupla_ ou o _iterador_ retornando um _iterador_ em ordem reversa. **Só vai virar uma lista reversa se for materializada**. Veja os exemplos abaixo:

In [ ]:
lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
reversed(lista)

In [ ]:
lista_reversa = list(reversed(lista))
lista_reversa

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

**Zip**


Zip pareia os elementos de uma série de _tuplas_, _listas_ ou outras sequências e retorna uma lista de tuplas. Olha:

In [ ]:
seq1 = 1, 2, 3
type(seq1)

tuple

In [ ]:
seq2 = ['a', 'b', 'c']

In [ ]:
zipped = list(zip(seq1, seq2))
zipped

[(1, 'a'), (2, 'b'), (3, 'c')]

Agora, o que aconteceria se juntarmos a esta operação uma sequência com um número de elementos diferentes?

In [ ]:
seq3 = ['i', 'j']

zipped2 = list(zip(seq1, seq2, seq3))

In [ ]:
zipped2

[(1, 'a', 'i'), (2, 'b', 'j')]

O que você pôde concluir?

### **3.3 Dicionários**

Trata-se de uma coleção de *chave* - *valor*, de tamanho flexível, em que _chave_ e _valor_ são objetos **Python**. Para criar um ***dicionário*** é neceśsario usar $\{$ $\}$ e dois pontos para separar ***chaves***-***valor***.

Exemplo:

In [ ]:
dicionario = {}

In [ ]:
dicionario['chave'] = 'valor'
dicionario

{'chave': 'valor'}

In [ ]:
dicionario['fruta'] = 'morango'
dicionario

{'chave': 'valor', 'fruta': 'morango'}

In [ ]:
dicionario['fruta']

'morango'

In [ ]:
dicionario[1] = True
dicionario

{1: True, 'chave': 'valor', 'fruta': 'morango'}

In [ ]:
dicionario[1]

True

In [ ]:
dicionario['Diego'] = 'Bilhalva'
dicionario['Diego']

'Bilhalva'

In [ ]:
dicionario[True] = 'Will'

In [ ]:
dicionario[True] #cuidado...saiba oq está fazendo

'Will'

In [ ]:
dicionario[1.23] = 'Teste' #cuidado...saiba oq está fazendo

In [ ]:
dicionario[1.23]

'Teste'

In [ ]:
dicionario[0] = 'Falso'

In [ ]:
dicionario[False]

'Falso'

In [ ]:
dicionario['endereco'] = 4234
dicionario

{0: 'Falso',
 1: 'Will',
 1.23: 'Teste',
 'Diego': 'Bilhalva',
 'chave': 'valor',
 'endereco': 4234,
 'fruta': 'morango'}

In [ ]:
dicionario.clear() #funcao in-place

In [ ]:
dicionario

{}

In [ ]:
dicionario['lista'] = [1, 2, 3, 4]
dicionario['tupla'] = (1, 2, 3, 4)
dicionario['a'] = 30
dicionario[30] = 'a'
dicionario

{30: 'a', 'a': 30, 'lista': [1, 2, 3, 4], 'tupla': (1, 2, 3, 4)}

In [ ]:
'tupla' in dicionario

True

In [ ]:
'fruta' in dicionario

False

É possível _apagar_ um chave e seu valor de uma lista com o comando $del$, veja:

In [ ]:
del dicionario #apaga a variável dicionario

In [ ]:
dicionario = {}
dicionario['lista'] = [1, 2, 3, 4]
dicionario['tupla'] = (1, 2, 3, 4)
dicionario['a'] = 30
dicionario[30] = 'a'
dicionario['qtty_alunos_turma'] = 7
dicionario['colorados'] = 3
dicionario['outros_times'] = dicionario['qtty_alunos_turma'] - dicionario['colorados']
dicionario

{30: 'a',
 'a': 30,
 'colorados': 3,
 'lista': [1, 2, 3, 4],
 'outros_times': 4,
 'qtty_alunos_turma': 7,
 'tupla': (1, 2, 3, 4)}

In [ ]:
del dicionario[30]
dicionario

{'a': 30,
 'colorados': 3,
 'lista': [1, 2, 3, 4],
 'outros_times': 4,
 'qtty_alunos_turma': 7,
 'tupla': (1, 2, 3, 4)}

Para retornar as chaves de um dicionário faça o seguinte:

In [ ]:
dicionario.keys()

dict_keys(['lista', 'tupla', 'a', 'qtty_alunos_turma', 'colorados', 'outros_times'])

In [ ]:
for chave in dicionario.keys():
  print('o valor da chave {0} é {1}'.format(chave, dicionario[chave]))

o valor da chave lista é [1, 2, 3, 4]
o valor da chave tupla é (1, 2, 3, 4)
o valor da chave a é 30
o valor da chave qtty_alunos_turma é 7
o valor da chave colorados é 3
o valor da chave outros_times é 4

No entanto se você quiser acrescentar uma outra coleção de dicionário a um dicionário existe, use o método $update()$, observe:

In [ ]:
dicionario_2 = {
    'qtos_alunos_tem_carro': 5
    ,'nome_aluno_mais_novo' : 'Pedro'
}
dicionario_2

{'nome_aluno_mais_novo': 'Pedro', 'qtos_alunos_tem_carro': 5}

In [ ]:
dicionario.update(dicionario_2)
dicionario

{'a': 30,
 'colorados': 3,
 'lista': [1, 2, 3, 4],
 'nome_aluno_mais_novo': 'Pedro',
 'outros_times': 4,
 'qtos_alunos_tem_carro': 5,
 'qtty_alunos_turma': 7,
 'tupla': (1, 2, 3, 4)}

---
---

### **3.4. List Comprehensions**

Caros alunos, agora vamos falar de um dos recursos mais interessantes do **Python**. Este recurso permite que você crie uma nova lista de modo conciso, filtrando os elementos de uma coleção, transformando os elementos ao passa o filtro, com uma expressão concisa. As **List Comprehensions** assumem o seguinte formato básico:

_`[expr for val in collection if condition]`_

Isso é equivalente ao laço a seguir:

```
result = []

for val in collection:
  if condition:
    result.append(expr)
```

A condição do filtro pode ser omitida, restando somente a expressão. Veja um exemplo:

In [ ]:
strings_a = 'Meu nome é Diego e eu sou um data scientist.'.split()
strings_a

['Meu', 'nome', 'é', 'Diego', 'e', 'eu', 'sou', 'um', 'data', 'scientist.']

In [ ]:
strings_b = [x.upper() for x in strings_a]
strings_b

['MEU', 'NOME', 'É', 'DIEGO', 'E', 'EU', 'SOU', 'UM', 'DATA', 'SCIENTIST.']

In [ ]:
strings_b = [x.upper() for x in strings_a if len(x) > 2]
strings_b

['MEU', 'NOME', 'DIEGO', 'SOU', 'DATA', 'SCIENTIST.']

In [ ]:
string_c = []

for x in strings_a:
  if len(x) > 2:
    string_c.append(x.upper())

string_c

['MEU', 'NOME', 'DIEGO', 'SOU', 'DATA', 'SCIENTIST.']

### **3.5 Exercícios de Fixação**

#### E9. ⏰(5min) Crie uma sequência de Fibonnaci usando listas com 20 termos.

In [2]:
fibonacci = [0, 1]
while len(fibonacci) < 20:
  fibonacci.append(fibonacci[len(fibonacci)-1] + fibonacci[len(fibonacci)-2])

print(fibonacci)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]

#### E10. ⏰(5min) Implemente um programa em Python que recebe como entrada uma string digitada pelo usuário e retorna a string invertida.

Veja o **exemplo**:
**Entrada** = "existem várias maneiras de inverter uma string"
**Saída** = "gnirts amu retrevni ed sarienam sairáv metsixe"

In [1]:
lista = [5,4,3,2,1]
list(reversed(lista))

[1, 2, 3, 4, 5]

#### E11. ⏰(5min) Colete os seguintes dados de um usuario armazenando as chaves e os valores num dicionario:
* Nome Completo
* Endereco Completo
* Telefone
* Cidade
* Estado
* Data de Nascimento

In [ ]:
dicionario = {
    'Nome Completo': str(input('Digite seu nome completo: '))
    , 'Endereço Completo': str(input('Digite seu endereço completo: '))
    , 'Telefone': str(input('Digite seu telefone: '))
    , 'Cidade': str(input('Digite sua cidade: '))
    , 'Estado': str(input('Digite seu estado: '))
    , 'Data de nascimento': str(input('Digite sua data de nascimento no formato dd/mm/aaaa: '))
}
print('.')
print('.')
print('.')
print('Segue abaixo os dados cadastrados:')
print('Nome Completo: {0}'.format(dicionario['Nome Completo']))
print('Endereço Completo: {0}'.format(dicionario['Endereço Completo']))
print('Telefone: {0}'.format(dicionario['Telefone']))
print('Cidade: {0}'.format(dicionario['Cidade']))
print('Estado: {0}'.format(dicionario['Estado']))
print('Data de nascimento: {0}'.format(dicionario['Data de nascimento']))

#### E12. ⏰(10min) Colete os dados de um dos colegas da turma e para aqueles com carreira profissional menor ou igual a média, classifique-o como "sub_grupo", "a" e os demais como "sub_grupo" "b", armazenando esta informação no mesmo dicionário.

Dado do Exercício: a média de carreira em anos é 4,7 anos

In [ ]:
dicionario = {'Nome Completo': 'teste', 'Endereco Completo': 'teste 123', 'Telefone User': 12521342}

dicionario['nome completo']

In [ ]:
teste = 4.7
type(teste)

In [ ]:
# sub_grupo_a = {}
# sub_grupo_b = {} 
dados_colega = {} #declaração dos dicionários

dados_colega['Nome'] = 'José William' #Atribuição dos dados
dados_colega['Idade'] = 40
dados_colega['CPF'] = 333333333
dados_colega['RG'] = 2222222222
dados_colega['Anos de trabalho'] = 20.5

# dados_colega
dados_colega.get('Anos de trabalho')

media = float(4.7) # variável
type(media)

if media <= dados_colega.get('Anos de trabalho'): #Lógica condicional
  dados_colega['sub_grupo'] = 'a'
else:
  dados_colega['sub_grupo'] = 'b'

dados_colega.get('sub_grupo')

#### E13. ⏰(15min) Crie um sistema que solicite ao usuário que informe "uma chave" e, se a chave existir no dicionário do exemplo anterior, devemos retornar a informação para o usuário.

Exemplo: O usuário solicita a "Cidade" e o sistema retorna "São Paulo".

In [3]:
dicionario = {'Cidade': 'Porto Alegre',
 'Data de Nascimento': '10 de janeiro de 2000',
 'Endereço Completo': 'Rua  xxxnúmero 500 apto. 600',
 'Estado': 'RS',
 'Nome Completo': 'William Matheus Franco',
 'Telefone': 33333333}

In [4]:
chave = input('Informe qual a chave vc deseja resgatar o valor: ')

if not chave in dicionario:
  dicionario[chave] = input('Eu não tenho esta chave. Informe um valor para eu cria-la: ')

print(dicionario[chave])

Informe qual a chave vc deseja resgatar o valor: Time de futebol
Eu não tenho esta chave. Informe um valor para eu cria-la: Colorado
Colorado

In [5]:
dicionario

{'Cidade': 'Porto Alegre',
 'Data de Nascimento': '10 de janeiro de 2000',
 'Endereço Completo': 'Rua  xxxnúmero 500 apto. 600',
 'Estado': 'RS',
 'Nome Completo': 'William Matheus Franco',
 'Telefone': 33333333,
 'Time de futebol': 'Colorado'}